#
# Makefile for VFM
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#
# Note 2! The CFLAGS definitions are now inherited from the
# parent makes..

#
# Makefile for the kernel VSB driver.
#

L_TARGET := roflash.a

export-objs := roflash.o

obj-y += roflash.o

include $(TOPDIR)/Rules.make
